na

diff --git a/.github/workflows/feature-to-backlog.yml b/.github/workflows/feature-to-backlog.yml
--- a/.github/workflows/feature-to-backlog.yml
+++ b/.github/workflows/feature-to-backlog.yml
@@ -37,6 +37,28 @@ jobs:
           echo "Got the issue id of $ISSUE_NODE_ID"
           echo "ISSUE_NODE_ID=$ISSUE_NODE_ID" >> "$GITHUB_ENV"
 
+      - name: Get ProjectV2 Issue ID
+        run: |
+          PROJECT_ID="PVT_kwHOB16rWM4ApMGw"
+          ISSUE_NODE_ID="${{ steps.get_issue.outputs.ISSUE_NODE_ID }}"
+
+          RESPONSE=$(curl -H "Authorization: bearer $PAT_TOKEN" \
+                -X POST \
+                -H "Content-Type: application/json" \
+                -d "{\"query\": \"query { node(id: \\\"$PROJECT_ID\\\") { ... on ProjectV2 { items(first: 100) { nodes { id content { ... on Issue { id } } } } } } }\"}" \
+                https://api.github.com/graphql)
+
+          PROJECT_ITEM_ID=$(echo "$RESPONSE" | jq -r ".data.node.items.nodes[] | select(.content.id == \"$ISSUE_NODE_ID\") | .id")
+          echo "ProjectV2 Item ID: $PROJECT_ITEM_ID"
+
+          if [ -z "$PROJECT_ITEM_ID" ]; then
+            echo "Error: ProjectV2Item ID not found!"
+            exit 1
+          fi
+
+          # Schreibe den Wert der ProjectV2Item ID als Ausgabe des Schritts
+          echo "ITEM_ID=$PROJECT_ITEM_ID" >> "$GITHUB_ENV"
+
       # Schritt 2: Teste den Zugriff auf die GitHub API mit dem PAT
       - name: Test PAT Access to GitHub API
         run: |
@@ -95,7 +117,7 @@ jobs:
           OPTION_ID="394f8d2b"
           
           echo "Project ID: $PROJECT_ID"
-          echo "Item ID: $ISSUE_NODE_ID"
+          echo "Item ID: $ITEM_ID"
           echo "Field ID: $FIELD_ID"
           echo "Option ID: $OPTION_ID"
         
@@ -103,11 +125,12 @@ jobs:
           RESPONSE=$(curl -H "Authorization: bearer ${{ secrets.PAT_TOKEN }}" \
                 -X POST \
                 -H "Content-Type: application/json" \
-                -d "{\"query\": \"mutation { updateProjectV2ItemFieldValue(input: { projectId: \\\"$PROJECT_ID\\\", itemId: \\\"$ISSUE_NODE_ID\\\", fieldId: \\\"$FIELD_ID\\\", value: { singleSelectOptionId: \\\"$OPTION_ID\\\" } }) { projectV2Item { id } } }\"}" \
+                -d "{\"query\": \"mutation { updateProjectV2ItemFieldValue(input: { projectId: \\\"$PROJECT_ID\\\", itemId: \\\"$ITEM_ID\\\", fieldId: \\\"$FIELD_ID\\\", value: { singleSelectOptionId: \\\"$OPTION_ID\\\" } }) { projectV2Item { id } } }\"}" \
                 https://api.github.com/graphql)
 
           # Ausgabe der API-Antwort
-          echo "Query: {\"query\": \"mutation { updateProjectV2ItemFieldValue(input: { projectId: \\\"$PROJECT_ID\\\", itemId: \\\"$ISSUE_NODE_ID\\\", fieldId: \\\"$FIELD_ID\\\", value: { singleSelectOptionId: \\\"$OPTION_ID\\\" } }) { projectV2Item { id } } }\"}"
+          echo "Query: {\"query\": \"mutation { updateProjectV2ItemFieldValue(input: { projectId: 
+          \\\"$PROJECT_ID\\\", itemId: \\\"$ITEM_ID\\\", fieldId: \\\"$FIELD_ID\\\", value: { singleSelectOptionId: \\\"$OPTION_ID\\\" } }) { projectV2Item { id } } }\"}"
           echo "GraphQL API Response: $RESPONSE"
 
           UPDATED_ITEM_ID=$(echo "$RESPONSE" | jq -r .data.updateProjectV2ItemFieldValue.projectV2Item.id)
